### ISSUE TITLE
Evaluate state log chunking layer

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#446]
When an entry that is too large gets written to BookKeeper, we see the following exception:

```
2015-12-17 16:24:29 ERROR org.apache.bookkeeper.proto.BookieRequestHandler: Unhandled exception occurred in I/O thread or handler
org.jboss.netty.handler.codec.frame.TooLongFrameException: Adjusted frame length exceeds 1048575: 3162300 - discarded
    at org.jboss.netty.handler.codec.frame.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:417)
    at org.jboss.netty.handler.codec.frame.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:405)
    at org.jboss.netty.handler.codec.frame.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:320)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

BK limits entries to 1 MB. We need a mechanism to slice this up.

**Comment by lbradstreet** [comment]
This is especially needed for state log compaction as the whole state may not compact down to 1MB.

**Comment by lbradstreet** [comment]
Also, tuning the write batch size is definitely preferable to chunking, though we may need a solution regardless.

**Comment by lbradstreet** [comment]
No longer relevant in 0.10.
