### ISSUE TITLE
Bookkeeper fails to start if cookie already exists in zookeeperBookkeeper fails to start if cookie already exists in zookeeper:

### ISSUE THREAD

**Issue by stefanbacon** [onyx-platform/onyx#471]
Bookkeeper fails to start if cookie already exists in zookeeper:

```
Caused by: org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /onyx/test/ledgers/cookies/xxx.xxx.xxx.xxx:3196
    at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:366)
    at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:466)
    at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:107)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:95)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:87)
    at onyx.state.bookkeeper.Bookie.start(bookkeeper.clj:35)
    at onyx.state.bookkeeper.BookieMonitor.start(bookkeeper.clj:71)
    at onyx.state.bookkeeper.BookieServers$fn__28021.invoke(bookkeeper.clj:105)
    at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
    at clojure.core$reduce.invoke(core.clj:6518)
    at clojure.core$mapv.invoke(core.clj:6616)
    at onyx.state.bookkeeper.BookieServers.start(bookkeeper.clj:104)
    at com.stuartsierra.component$fn__16299$G__16293__16301.invoke(component.clj:4)
    at com.stuartsierra.component$fn__16299$G__16292__16304.invoke(component.clj:4)
    at clojure.lang.Var.invoke(Var.java:379)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:632)
    at com.stuartsierra.component$try_action.invoke(component.clj:116)
    at com.stuartsierra.component$update_system$fn__16350.invoke(component.clj:138)
    at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
    at clojure.core$reduce.invoke(core.clj:6518)
    at com.stuartsierra.component$update_system.doInvoke(component.clj:134)
    at clojure.lang.RestFn.invoke(RestFn.java:445)
    at com.stuartsierra.component$start_system.invoke(component.clj:162)
    at onyx.system.OnyxDevelopmentEnv$fn__30707.invoke(system.clj:64)
    at onyx.system$rethrow_component.invoke(system.clj:53)
    at onyx.system.OnyxDevelopmentEnv.start(system.clj:63)
    at onyx.api$start_env.invoke(api.clj:327)
    at onyx.api$start_env.invoke(api.clj:324)
```
`:onyx.bookkeeper/delete-server-data?` only deletes `:onyx.bookkeeper/base-journal-dir` and `:onyx.bookkeeper/base-ledger-dir` see https://github.com/onyx-platform/onyx/blob/5a967332e4b2707b585ac464b673eb6918b10307/src/onyx/state/bookkeeper.clj
and doesn't clear zookeeper data.

we'll also have this problem in case of unclean shutdown

**Comment by stefanbacon** [comment]
my bookkeeper dirs and zookeeper data was out of sync. can't reproduce issue on clean environment

**Comment by gardnervickers** [comment]
Re opened as this still occurs even if you clean your server data. Quick, unclean restarts of a Bookie dont give the Cookie in ZK time to expire.

**Comment by MichaelDrogalis** [comment]
Patch merged into develop.

**Comment by neverfox** [comment]
I still had this happen to me on an unclean shutdown (my peers died under memory pressure). I have `:onyx.bookkeeper/delete-server-data? true`. Not sure how to recover without losing checkpoints etc.

**Comment by gardnervickers** [comment]
@neverfox Could you please provide Onyx version and the logs indicating you ran into this issue?

**Comment by neverfox** [comment]
Unfortunately, I don't have them anymore as it was a transient development docker configuration. I'll keep a look out for a reoccurrence.

**Comment by anujsrc** [comment]
@gardnervickers - I think this is similar to the one being discussed in this issue. Unclean shutdown is giving the following error on restart. I am using Onyx 0.9.12 and external zookeeper 3.4.6. Here are the logs-

```
16-11-20 08:44:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3196
16-11-20 08:44:12 localhost INFO [onyx.state.bookkeeper:27] - Deleting Bookie dirs /tmp/bookkeeper_journal/3196 ; /tmp/bookkeeper_ledger/3196
16-11-20 13:17:00 localhost INFO [onyx.static.logging-configuration:35] - Starting Logging Configuration
16-11-20 13:17:00 localhost INFO [onyx.log.zookeeper:97] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-11-20 13:18:34 localhost INFO [onyx.state.bookkeeper:62] - Starting BookKeeper server on port 3196
16-11-20 13:18:34 localhost INFO [onyx.state.bookkeeper:63] - Creating Bookie dirs /tmp/bookkeeper_journal/3196 ; /tmp/bookkeeper_ledger/3196
16-11-20 13:18:34 localhost INFO [onyx.state.bookkeeper:104] - Starting BookKeeper Monitor service
16-11-20 13:18:34 localhost INFO [onyx.state.bookkeeper:62] - Starting BookKeeper server on port 3197
16-11-20 13:18:34 localhost INFO [onyx.state.bookkeeper:63] - Creating Bookie dirs /tmp/bookkeeper_journal/3197 ; /tmp/bookkeeper_ledger/3197
16-11-20 13:18:35 localhost INFO [onyx.state.bookkeeper:104] - Starting BookKeeper Monitor service
16-11-20 13:18:35 localhost FATAL [onyx.system:84] - 
                          clojure.core/eval        core.clj: 3105
                                        ...                      
                              user/eval1483       REPL Input     
                                        ...                      
                      clojure.core/load-one        core.clj: 5697
                                        ...                      
                          clojure.core/load        core.clj: 5876
                          clojure.core/load        core.clj: 5892
                       clojure.core/load/fn        core.clj: 5893
                                        ...                      
                         onyx.api/start-env         api.clj:  338
       onyx.system.OnyxDevelopmentEnv/start      system.clj:   90
              onyx.system/rethrow-component      system.clj:   82
          onyx.system.OnyxDevelopmentEnv/fn      system.clj:   91
    com.stuartsierra.component/start-system  component.cljc:  163
                                        ...                      
   com.stuartsierra.component/update-system  component.cljc:  129
   com.stuartsierra.component/update-system  component.cljc:  135
                        clojure.core/reduce        core.clj: 6544
                                        ...                      
com.stuartsierra.component/update-system/fn  component.cljc:  139
      com.stuartsierra.component/try-action  component.cljc:  117
                         clojure.core/apply        core.clj:  648
                                        ...                      
  com.stuartsierra.component/eval11602/fn/G  component.cljc:    5 (repeats 2 times)
  onyx.state.bookkeeper.BookieServers/start  bookkeeper.clj:  127
                          clojure.core/mapv        core.clj: 6618
                        clojure.core/reduce        core.clj: 6544
                                        ...                      
                       clojure.core/mapv/fn        core.clj: 6627
     onyx.state.bookkeeper.BookieServers/fn  bookkeeper.clj:  128
  onyx.state.bookkeeper.BookieMonitor/start  bookkeeper.clj:   94
onyx.state.bookkeeper.BookieComponent/start  bookkeeper.clj:   72
                       clojure.core/ex-info        core.clj: 4617
clojure.lang.ExceptionInfo: The Bookie server failed to start because a cookie or
                                                       ledger already exists for this host. Set
                                                       :onyx.bookkeeper/delete-server-data? true to format
                                                       the Bookie environment on component shutdown.
clojure.lang.ExceptionInfo: Error in component :bookkeeper in system onyx.system.OnyxDevelopmentEnv calling #'com.stuartsierra.component/start
     component: #<Bookie Servers>
      function: #'com.stuartsierra.component/start
        reason: :com.stuartsierra.component/component-function-threw-exception
        system: #onyx.system.OnyxDevelopmentEnv{:monitoring #<NoOp Monitoring Agent>, :logging-config #<Logging Configuration>, :bookkeeper #<Bookie Servers>, :log #<ZooKeeper Component>}
    system-key: :bookkeeper
```
How do I recover from this issue?

**Comment by anujsrc** [comment]
Delete the ZK /ledger node and its children to recover

**Comment by gardnervickers** [comment]
@anujsrc Thanks for the info, did you have `:onyx.bookkeeper/delete-server-data?` set to `true` and it was being ignored?

**Comment by anujsrc** [comment]
@gardnervickers - Initially, I didn't have that set. I did add it after clean-up and now I can see the logs and it says it is clearing up the cookie.

```
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3196
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3196
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3197
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3198
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3196
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3197
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3198
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3197
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3197
16-11-20 15:45:12 localhost INFO [onyx.state.bookkeeper:25] - Deleting Bookie cookie /ledgers/cookies/127.0.0.1:3198
```
Hope this is a good sign.

**Comment by MichaelDrogalis** [comment]
Working as expected. :)

**Comment by neverfox** [comment]
@gardnervickers Here are the logs (running 0.9.12-20161026.105408-4):

```
Starting peer-group
16-11-22 17:59:40 onyx-364793963-0mbn0 INFO [onyx.static.logging-configuration:35] - Starting Logging Configuration
16-11-22 17:59:40 onyx-364793963-0mbn0 INFO [onyx.messaging.aeron:187] - Starting Aeron Peer Group
Starting env
16-11-22 17:59:40 onyx-364793963-0mbn0 INFO [onyx.static.logging-configuration:35] - Starting Logging Configuration
16-11-22 17:59:40 onyx-364793963-0mbn0 INFO [onyx.log.zookeeper:97] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-11-22 17:59:40 onyx-364793963-0mbn0 INFO [onyx.log.zookeeper:97] - Starting ZooKeeper client connection. If Onyx hangs here it may indicate a difficulty connecting to ZooKeeper.
16-11-22 17:59:41 onyx-364793963-0mbn0 INFO [onyx.peer.communicator:26] - Starting Log Writer
16-11-22 17:59:41 onyx-364793963-0mbn0 INFO [onyx.peer.communicator:47] - Starting Replica Subscription
16-11-22 17:59:41 onyx-364793963-0mbn0 INFO [onyx.static.logging-configuration:35] - Starting Logging Configuration
16-11-22 17:59:41 onyx-364793963-0mbn0 FATAL [onyx.system:84] -
                 nav_keyword_onyx.core.main
                                        ...
                nav-keyword-onyx.core/-main        core.clj:   86
                nav-keyword-onyx.core/-main        core.clj:   97
                   lib-onyx.peer/start-peer        peer.clj:   11
                         onyx.api/start-env         api.clj:  339
       onyx.system.OnyxDevelopmentEnv/start      system.clj:   90
              onyx.system/rethrow-component      system.clj:   82
          onyx.system.OnyxDevelopmentEnv/fn      system.clj:   91
    com.stuartsierra.component/start-system  component.cljc:  163
                                        ...
   com.stuartsierra.component/update-system  component.cljc:  129
   com.stuartsierra.component/update-system  component.cljc:  135
                        clojure.core/reduce        core.clj: 6544
                                        ...
com.stuartsierra.component/update-system/fn  component.cljc:  139
      com.stuartsierra.component/try-action  component.cljc:  117
                         clojure.core/apply        core.clj:  648
                                        ...
            com.stuartsierra.component/fn/G  component.cljc:    5 (repeats 2 times)
  onyx.state.bookkeeper.BookieServers/start  bookkeeper.clj:  127
                          clojure.core/mapv        core.clj: 6618
                        clojure.core/reduce        core.clj: 6544
                                        ...
                       clojure.core/mapv/fn        core.clj: 6627
     onyx.state.bookkeeper.BookieServers/fn  bookkeeper.clj:  128
  onyx.state.bookkeeper.BookieMonitor/start  bookkeeper.clj:   94
onyx.state.bookkeeper.BookieComponent/start  bookkeeper.clj:   72
                       clojure.core/ex-info        core.clj: 4617
clojure.lang.ExceptionInfo: The Bookie server failed to start because a cookie or
                                                       ledger already exists for this host. Set
                                                       :onyx.bookkeeper/delete-server-data? true to format
                                                       the Bookie environment on component shutdown.
clojure.lang.ExceptionInfo: Error in component :bookkeeper in system onyx.system.OnyxDevelopmentEnv calling #'com.stuartsierra.component/start
     component: #<Bookie Servers>
      function: #'com.stuartsierra.component/start
        reason: :com.stuartsierra.component/component-function-threw-exception
        system: #onyx.system.OnyxDevelopmentEnv{:monitoring #<NoOp Monitoring Agent>, :logging-config #<Logging Configuration>, :bookkeeper #<Bookie Servers>, :log #<ZooKeeper Component>}
    system-key: :bookkeeper

Exception in thread "main" clojure.lang.ExceptionInfo: The Bookie server failed to start because a cookie or
                           ledger already exists for this host. Set
                           :onyx.bookkeeper/delete-server-data? true to format
                           the Bookie environment on component shutdown. {}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at onyx.state.bookkeeper.BookieComponent.start(bookkeeper.clj:72)
	at onyx.state.bookkeeper.BookieMonitor.start(bookkeeper.clj:94)
	at onyx.state.bookkeeper.BookieServers$fn__17155.invoke(bookkeeper.clj:128)
	at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$mapv.invokeStatic(core.clj:6618)
	at clojure.core$mapv.invoke(core.clj:6618)
	at onyx.state.bookkeeper.BookieServers.start(bookkeeper.clj:127)
	at com.stuartsierra.component$fn__6964$G__6958__6966.invoke(component.cljc:5)
	at com.stuartsierra.component$fn__6964$G__6957__6969.invoke(component.cljc:5)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
	at com.stuartsierra.component$try_action.invoke(component.cljc:116)
	at com.stuartsierra.component$update_system$fn__7015.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:155)
	at onyx.system.OnyxDevelopmentEnv$fn__19516.invoke(system.clj:91)
	at onyx.system$rethrow_component.invokeStatic(system.clj:82)
	at onyx.system$rethrow_component.invoke(system.clj:80)
	at onyx.system.OnyxDevelopmentEnv.start(system.clj:90)
	at onyx.api$start_env.invokeStatic(api.clj:339)
	at onyx.api$start_env.invoke(api.clj:335)
	at lib_onyx.peer$start_peer.invokeStatic(peer.clj:11)
	at lib_onyx.peer$start_peer.invoke(peer.clj:4)
	at nav_keyword_onyx.core$_main.invokeStatic(core.clj:97)
	at nav_keyword_onyx.core$_main.doInvoke(core.clj:86)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at nav_keyword_onyx.core.main(Unknown Source)
16-11-22 17:59:41 onyx-364793963-0mbn0 INFO [onyx.log.commands.submit-job:92] - Job ID c7c13260-4948-4b62-9c44-20e496478797 has been submitted with tenancy ID 0.9.12-SNAPSHOT, but received no virtual peers to start its execution.
                     Tasks each require at least one peer to be started, and may require more if :onyx/n-peers or :onyx/min-peers is set.
                     If you were expecting your job to start now, either start more virtual peers or choose a different job scheduler, or wait for existing jobs to finish.
16-11-22 17:59:42 onyx-364793963-0mbn0 INFO [onyx.log.commands.submit-job:92] - Job ID 1d62d1c3-42cf-4b8a-9427-f9b5920a89f4 has been submitted with tenancy ID 0.9.12-SNAPSHOT, but received no virtual peers to start its execution.
                     Tasks each require at least one peer to be started, and may require more if :onyx/n-peers or :onyx/min-peers is set.
                     If you were expecting your job to start now, either start more virtual peers or choose a different job scheduler, or wait for existing jobs to finish.
16-11-22 17:59:43 onyx-364793963-0mbn0 INFO [onyx.log.failure-detector:36] - Starting peer failure detector
16-11-22 17:59:43 onyx-364793963-0mbn0 INFO [onyx.log.failure-detector:42] - Stopping peer failure detector
16-11-22 17:59:43 onyx-364793963-0mbn0 INFO [onyx.log.failure-detector:30] - Stopping peer failure detector monitor thread
```

Here's our config:
```
{:onyx/tenancy-id   #profile {:default "1"
                              :docker  #env ONYX_ID}
 :zookeeper/address #profile {:default "127.0.0.1:2188"
                              :docker  #or [#env ZOOKEEPER_ADDR "zookeeper:2181"]}
 :onyx.log/config   #profile {:default {}
                              :docker  {:level :info}}
 :env-config
 {:onyx/tenancy-id                     ^:ref [:onyx/tenancy-id]
  :onyx.bookkeeper/server?             true
  :onyx.bookkeeper/local-quorum?       true
  :onyx.bookkeeper/delete-server-data? true
  :onyx.bookkeeper/local-quorum-ports  [3196 3197 3198]
  :onyx.bookkeeper/port                3196
  :zookeeper/address                   ^:ref [:zookeeper/address]
  :zookeeper/server?                   #profile {:default true
                                                 :docker  false}
  :zookeeper.server/port               2188
  :onyx.log/config                     ^:ref [:onyx.log/config]}
 :peer-config
 {:onyx/tenancy-id                       ^:ref [:onyx/tenancy-id]
  :zookeeper/address                     ^:ref [:zookeeper/address]
  :onyx.peer/job-scheduler               :onyx.job-scheduler/balanced
  :onyx.peer/zookeeper-timeout           60000
  :onyx.messaging/allow-short-circuit?   #profile {:default false
                                                   :docker  true}
  :onyx.messaging/impl                   :aeron
  :onyx.messaging/bind-addr              #or [#env BIND_ADDR "localhost"]
  :onyx.messaging/peer-port              40200
  :onyx.messaging.aeron/embedded-driver? #profile {:default true
                                                   :docker  false}
  :onyx.log/config                       ^:ref [:onyx.log/config]}}
```
